# Generated by Django 5.0 on 2024-01-04 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('describtion', models.TextField(max_length=300)),
                ('is_complete', models.BooleanField(default=False)),
                ('task_assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
