# Generated by Django 5.0 on 2024-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_is_complete_taskmodel_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='complete',
            field=models.BooleanField(),
        ),
    ]
